/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f0xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



int main(void)
{
	RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
	GPIOA->MODER |= GPIO_MODER_MODER5_0;

	/* SOS vector	*/
	//uint8_t sos_v[] = {1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0};
	//int i;

	/* SOS binary sequence */
	const uint32_t sos_b  = 0b10101000111011101110001010100000;
	const uint32_t mask_b	= 0b10000000000000000000000000000000;

	/* Loop forever */

	/*
	for(;;){
		for (i = 0; i<sizeof(sos_v);i++){

			if(sos_v[i]==1) GPIOA->BSRR = (1<<5); 				// set

			else GPIOA->BRR = (1<<5); 							// reset

			for (volatile uint32_t i = 0; i < 100000; i++) {}
		}

		//GPIOA->ODR ^= (1<<5); 								// toggle
		for (volatile uint32_t j = 0; j < 100000; j++) {}

	}
	*/
	for(;;){
			for (uint32_t b = 0; b<32;b++){

				if((sos_b << b) & mask_b)  GPIOA->BSRR = (1<<5); 				// set

				else GPIOA->BRR  = (1<<5); 				// reset

				for (volatile uint32_t i = 0; i < 100000; i++) {}
			}

	}
}
